# Generated by Django 6.0.5 on 2026-06-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Austin Chamber of Commerce', max_length=255)),
                ('state', models.CharField(db_index=True, help_text='2-letter US state code (e.g., TX, FL, GA)', max_length=2)),
                ('city_or_region', models.CharField(blank=True, help_text='e.g., Austin', max_length=100, null=True)),
                ('directory_url', models.URLField(blank=True, help_text='The source URL scraped', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the front-end market')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chamber Directories',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChamberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('state', models.CharField(help_text='2-letter US state code (e.g., TX)', max_length=2)),
                ('city_or_region', models.CharField(help_text='e.g., Austin', max_length=100)),
                ('chamber_name', models.CharField(help_text='e.g., Austin Chamber of Commerce', max_length=255)),
                ('chamber_url', models.URLField(help_text='Direct link to the target directory page', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('scraping', 'Scraping In Progress'), ('completed', 'Completed & Live'), ('rejected', 'Unfeasible/Requires Refund')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chamberlead',
            name='directory',
            field=models.ForeignKey(blank=True, help_text='The nationwide chamber asset this lead belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.chamberdirectory'),
        ),
    ]
