# Generated by Django 6.0.5 on 2026-06-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_chamberdirectory_chamberrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberrequest',
            name='chambers_count',
            field=models.IntegerField(choices=[(1, 'Single Local Area / Chamber Target ($9.99)'), (5, 'Regional Bundle Package (Up to 5 Areas) ($49.00)'), (10, 'Expanded Regional Pack (Up to 10 Areas) ($99.00)'), (20, 'Enterprise Multi-Region / Full State (Custom Quote - $10/ch)')], default=1, help_text='The requested data batch sizing tier'),
        ),
        migrations.AddField(
            model_name='chamberrequest',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=9.99, help_text='Calculated transaction price or quote evaluation benchmark', max_digits=6),
        ),
        migrations.AlterField(
            model_name='chamberrequest',
            name='chamber_name',
            field=models.TextField(help_text='List the specific Chambers of Commerce (one per line or comma-separated)'),
        ),
        migrations.AlterField(
            model_name='chamberrequest',
            name='chamber_url',
            field=models.TextField(help_text='Provide the direct links showing their public online membership directory index layout'),
        ),
        migrations.AlterField(
            model_name='chamberrequest',
            name='city_or_region',
            field=models.CharField(help_text='e.g., Austin, Round Rock, Buda', max_length=255),
        ),
    ]
