# Generated by Django 6.0.5 on 2026-06-14 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_order_orderitem_userpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpurchase',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', True)), fields=('user', 'directory'), name='unique_user_directory_purchase'),
        ),
        migrations.AddConstraint(
            model_name='userpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('directory__isnull', True)), fields=('user', 'lead'), name='unique_user_lead_purchase'),
        ),
    ]
