# Generated by Django 6.0.5 on 2026-06-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_userpurchase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberrequest',
            name='console_logs',
            field=models.TextField(blank=True, default='', help_text='Real-time scrolling terminal output from worker threads'),
        ),
    ]
