# Generated by Django 6.0.5 on 2026-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_chamberrequest_console_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberdirectory',
            name='staged_leads_data',
            field=models.JSONField(blank=True, default=list, help_text='Temporary storage for previews'),
        ),
    ]
